// app/api/foodData/route.js
export async function GET() {
  const foodData = [
    {
      name: "Spaghetti Carbonara",
      ingredients: [
        "spaghetti",
        "tojás",
        "bacon",
        "parmezán sajt",
        "fekete bors",
      ],
      image: "/foods/carbonara.webp",
      price: "2000",
      vegetarian: false,
    },
    {
      name: "Margherita Pizza",
      ingredients: [
        "pizza tészta",
        "paradicsomszósz",
        "mozzarella",
        "bazsalikom",
      ],
      image: "/foods/margherita.jpg",
      price: "2500",
      vegetarian: true,
    },
    {
      name: "Húsleves",
      ingredients: ["marhahús", "zöldségek", "hagymák", "fűszerek"],
      image: "/foods/husleves.webp",
      price: "1000",
      vegetarian: false,
    },
    {
      name: "Töltött Káposzta",
      ingredients: ["savanyú káposzta", "darálthús", "rizs", "fűszerek"],
      image: "/foods/kaposzta.jpg",
      price: "2500",
      vegetarian: false,
    },
    {
      name: "Lasagne",
      ingredients: [
        "lasagne tészta",
        "darálthús",
        "paradicsomszósz",
        "béchamel szósz",
        "sajt",
      ],
      image: "/foods/lasagne.jpg",
      price: "3000",
      vegetarian: false,
    },
    {
      name: "Sült Csirke",
      ingredients: ["csirke", "burgonya", "fűszerek", "olívaolaj"],
      image: "/foods/csirke.jpg",
      price: "3500",
      vegetarian: false,
    },
    {
      name: "Vegetáriánus Burrito",
      ingredients: ["tortilla", "rizs", "bab", "zöldségek", "avokádó"],
      image: "/foods/vegetable-burrito.webp",
      price: "2500",
      vegetarian: true,
    },
    {
      name: "Gulyásleves",
      ingredients: [
        "marhahús",
        "burgonya",
        "zöldségek",
        "fűszerek",
        "pörkölt alap",
      ],
      image: "/foods/gulyas.jpeg",
      price: "2000",
      vegetarian: false,
    },
    {
      name: "Rántott Hal",
      ingredients: ["hal filé", "tojás", "zsemlemorzsa", "fűszerek", "citrom"],
      image: "/foods/hal.jpg",
      price: "2000",
      vegetarian: false,
    },
    {
      name: "Tzatziki",
      ingredients: ["joghurt", "uborka", "fokhagyma", "olívaolaj", "fűszerek"],
      image: "/foods/tzatziki.jpg",
      price: "1000",
      vegetarian: true,
    },
    {
      name: "Chili con Carne",
      ingredients: ["darálthús", "bab", "paradicsom", "fűszerek", "chili"],
      image: "/foods/chilli.jpg",
      price: "2000",
      vegetarian: false,
    },
    {
      name: "Pulykamell Sült Zöldségekkel",
      ingredients: ["pulykamell", "burgonya", "répa", "brokkoli", "fűszerek"],
      image: "/foods/pulyka.jpg",
      price: "3500",
      vegetarian: false,
    },
    {
      name: "Frittata",
      ingredients: ["tojás", "zöldségek", "sajt", "fűszerek"],
      image: "/foods/frittata.jpeg",
      price: "1500",
      vegetarian: true,
    },
    {
      name: "Pasta Pesto",
      ingredients: [
        "spaghetti",
        "bazsalikomos pesto",
        "parmezán sajt",
        "paradicsom",
      ],
      image: "/foods/pesto.jpg",
      price: "1500",
      vegetarian: true,
    },
    {
      name: "Pad Thai",
      ingredients: [
        "rizstészta",
        "tojás",
        "tenger gyümölcsei",
        "zöldségek",
        "tamari szósz",
      ],
      image: "/foods/thai.jpeg",
      price: "4000",
      vegetarian: false,
    },
    {
      name: "Kürtőskalács",
      ingredients: ["liszt", "cukor", "élesztő", "vaj", "fűszerek"],
      image: "/foods/kalacs.webp",
      price: "1500",
      vegetarian: true,
    },
    {
      name: "Pancakes",
      ingredients: ["liszt", "tojás", "tej", "cukor", "szirup"],
      image: "/foods/palacsinta.jpg",
      price: "1500",
      vegetarian: true,
    },
    {
      name: "Saláta Caesar",
      ingredients: [
        "saláta",
        "csirke",
        "parmezán sajt",
        "crouton",
        "caesar öntet",
      ],
      image: "/foods/cezar.jpg",
      price: "1500",
      vegetarian: false,
    },
  ];

  return new Response(JSON.stringify(foodData), {
    headers: { "Content-Type": "application/json" },
  });
}
