import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Component } from "./components/Navbar";
import { FooterComponent } from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"], // normál és félkövér
  display: "swap",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.className} ${geistMono.variable} antialiased`}
      >
        <Component />
        {children}

        <FooterComponent />
      </body>
    </html>
  );
}
