import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "./components/Navbar";
import { FooterComponent } from "./components/Footer";
import Head from "next/head";
import { CartProvider } from "./context/cart-context";
import FloatingBasket from "./components/FloatingBasket";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"], // normál és félkövér
  display: "swap",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Bolyhos Étterem - Finom étkek, barátságos környezet."
        />
        <meta
          name="keywords"
          content="étterem, étkezés, rendelés, bolyhos, étlap"
        />
        <meta name="Roland Toth" content="Bolyhos Étterem" />
        <title>Bolyhos Étterem</title>
      </Head>
      <body
        className={`${geistSans.variable} ${poppins.className} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <NavbarComponent />
          {children}
          <FloatingBasket />
          <FooterComponent />
          <Toaster />
        </CartProvider>
      </body>
    </html>
  );
}
